### ISSUE TITLE
Getting- 'ReferenceError: navigator is not defined' on importing 'shaka-player'

### ISSUE THREAD

**Issue by devjyotik200** [amit08255/shaka-player-react-with-ui-config#10]
Hey @amit08255 

I am using the shaka-player version 4.3.6 and i am trying to import it using `import shaka from 'shaka-player/dist/shaka-player.ui'`.

However i am getting the Navigator not defined error. 
PS:- I am already using this component in client side.

Do you have any idea how to resolve this?

<img width="892" alt="Screenshot 2023-06-15 at 6 55 09 PM" src="https://github.com/amit08255/shaka-player-react-with-ui-config/assets/59660191/ff9ce921-e533-43f0-95d1-5e1301257b18">

**Comment by amit08255** [comment]
Hello there @devjyotik200
Have you tried importing your video player component like below:

```js
import dynamic from 'next/dynamic';

const VideoComponent=dynamic(import ("../components/ShakaPlayer"),{ssr:false});
```

**Comment by devjyotik200** [comment]
> Hello there @devjyotik200 Have you tried importing your video player component like below:
> 
> ```js
> import dynamic from 'next/dynamic';
> 
> const VideoComponent=dynamic(import ("../components/ShakaPlayer"),{ssr:false});
> ```

Yes @amit08255 already tried this.

**Comment by amit08255** [comment]
Can you please share the part of the component?

**Comment by devjyotik200** [comment]
```
import StaticImage from 'shared/StaticImage'
import React from 'react'
import dynamic from 'next/dynamic'
import 'shaka-player/dist/controls.css'
import shaka from 'shaka-player/dist/shaka-player.ui'
import { useEffect, useRef } from 'react'


const STATIC_PATH = process.env.NEXT_PUBLIC_BASE_PATH

function ItutorVideoPlayer() {
    const videoComponent = useRef(null)
    const videoContainer = useRef(null)

    const onErrorEvent = (event) => {
        onError(event.detail)
    }

    const onError = (error) => {
        console.error('Error code', error.code, 'object', error)
    }

    useEffect(() => {
        var manifestUri =
            'https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd'
        const video = videoComponent.current
        // const videoContain = videoContainer.current
        var player = shaka.Player(video)

        let uiConfig = {}

        uiConfig['controlPanelElements'] = [
            'mute',
            'volume',
            'time_and_duration',
            'fullscreen',
            'overflow_menu',
        ]

        const ui = shaka.ui.Overlay(
            player,
            videoContainer.current,
            videoComponent.current
        )

        ui.configure(uiConfig)
        ui.getControls()

        player.addEventListener('error', onErrorEvent)
        player
            .load(manifestUri)
            .then(function () {
                // This runs if the asynchronous load is successful.
                console.log('The video has now been loaded!')
            })
            .catch(onError) // onError is executed if the asynchronous load fails.
    }, [])

    return (
        <div className="video-container" ref={videoContainer}>
            <video
                className="shaka-video"
                ref={videoComponent}
                // poster="//shaka-player-demo.appspot.com/assets/poster.jpg"
            />
        </div>
    )
```

This is the player component

**Comment by devjyotik200** [comment]
@amit08255 I think this is because of the upgraded shaka-player version

**Comment by amit08255** [comment]
No. I think this is because you are not using `dynamic` method. First create a simple Shaka player component just like you did. In the other component where you want to use it, use the `dynamic` method just like I gave in example above.

Reference can be found in this file: https://github.com/amit08255/shaka-player-react-with-ui-config/blob/master/nextjs-shaka-player/pages/index.js

**Comment by devjyotik200** [comment]
Doing the exact same 
```
const ItutorVideoPlayer = dynamic(() => import('./ItutorVideoPlayer'), {
    ssr: false,
})
```

**Comment by amit08255** [comment]
Give me some minutes. Will be back with a solution.

**Comment by devjyotik200** [comment]
Okay sure, thanks.
Can you upgrade your shaka-player and check once?

**Comment by amit08255** [comment]
Working on latest version. Pushed upgraded example. Try running that directly if it works for you.

<img width="1437" alt="image" src="https://github.com/amit08255/shaka-player-react-with-ui-config/assets/28493237/f313d36f-d02e-4317-8636-97fb430be2f8">

**Comment by devjyotik200** [comment]
It's working when i run your latest code, but its not working for my web app. psyc

**Comment by devjyotik200** [comment]
<img width="1728" alt="Screenshot 2023-06-15 at 9 38 15 PM" src="https://github.com/amit08255/shaka-player-react-with-ui-config/assets/59660191/a1f49a1b-848c-456f-a3c2-12d090b1eca7">
<img width="1728" alt="Screenshot 2023-06-15 at 9 38 45 PM" src="https://github.com/amit08255/shaka-player-react-with-ui-config/assets/59660191/55b2c573-3c10-4d9b-a842-9b5948f405d5">

**Comment by amit08255** [comment]
I think you should check your package version once. Separate the component in a demo page and try once.

**Comment by devjyotik200** [comment]
It's working when i moved my component to some other folder. Any idea why?

**Comment by amit08255** [comment]
I am suspecting your video player component is being imported during SSR and rendering during SSR. You need to import using `dynamic` with SSR set to false.

**Comment by devjyotik200** [comment]
Okay. Thanks a ton.
