### ISSUE TITLE
may wrong const def for variable

### ISSUE THREAD

**Issue by sl45sms** [amit08255/shaka-player-react-with-ui-config#2]
https://github.com/amit08255/shaka-player-react-with-ui-config/blob/43c3b8fccb190f91e2d81629a12a2380607aa4a2/with-ui-configuration/src/components/VideoPlayer.js#L55

Cause you set attributes on next line, convert `const` to `var` or `let`

**Comment by amit08255** [comment]
@sl45sms No that's correct. Please read about JavaScript const. https://www.geeksforgeeks.org/javascript-const/
