### ISSUE TITLE
How to playe m3u8 instead lf mpd 

### ISSUE THREAD

**Issue by md-fahad-ali32** [amit08255/shaka-player-react-with-ui-config#8]
After changing mpd file i added some m3u8 but doesn't work please help..

**Comment by amit08255** [comment]
Hi @sploit30
Please try with this m3u8 URL if its working for you:
https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8

**Comment by md-fahad-ali32** [comment]
I am using isp iptv m3u8 link is it supported link :
http://103.81.104.118/hls/stream24.m3u8
