### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by sunknudsen** [amit08255/shaka-player-react-with-ui-config#9]
Hey @amit08255,

Thanks for sharing these reference implementations.

Did you manage to get server side rendering to work on React?

Getting `ReferenceError: document is not defined` error.

**Comment by amit08255** [comment]
Hi. To use shaka player with React that supports SSR. You will need to make sure that the component which uses shaka player is only loaded on client side.

In NextJS it can be done very easily using dynamic feature which allows to import component dynamically and we can set if the component should be loaded on SSR.

Let me know if this answers the query.
